### ISSUE TITLE
Default policies from other lightning nodes

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/lnp-core#12]
This library defines `Policies`: a set of requirements against which channel parameters, proposed to a local node are checked. These policies strictly implement BOLT-2 requirements for processing `open_message` and `accept_message` by a receiving node.

One can read about what these policies are about just by checking doc comments:
https://github.com/LNP-BP/lnp-core/blob/0bd54b92521baa9663a5400a556b391aeafc9de1/src/bolt/channel.rs#L181-L221

Policy is normally provided by a specific node implementation (like LNP Node) to the channel constructor and is read from a user configuration file. However, if the node is just got initiated it will be good to have some preset of the policies which an unexpirienced user can choose from.

For now, we define our own preset for policy configuration here:
https://github.com/LNP-BP/lnp-core/blob/0bd54b92521baa9663a5400a556b391aeafc9de1/src/bolt/channel.rs#L226-L258

However the task is to look/dig into c-lightning, LND and Eclair code and extract their policy defaults and fill them into here:
https://github.com/LNP-BP/lnp-core/blob/0bd54b92521baa9663a5400a556b391aeafc9de1/src/bolt/channel.rs#L261-L274

@grunch I can't assign this task (some strange GitHub bug), so I am asking you to look at it here.

**Comment by grunch** [comment]
I'll be working on it 😃
