### ISSUE TITLE
Review and write unit tests for BOLT policy checks

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/lnp-core#13]
Related to #12: we need to have a unit tests to check that the policies actually work as required by BOLT-2

The actual code that should be reviewed (by comparing spec requirements) and unit-tested against the spec is this one:
https://github.com/LNP-BP/lnp-core/blob/0bd54b92521baa9663a5400a556b391aeafc9de1/src/bolt/channel.rs#L276-L479

Asking @grunch for a help here as well

**Comment by grunch** [comment]
Awesome, on it !!!
