### ISSUE TITLE
Create dedicated LightningTimeStamp wrapper over u32

### ISSUE THREAD

**Issue by rajarshimaitra** [LNP-BP/lnp-core#2]
Create a dedicated TimeStamp structure for all timestamps in LN messages.

**Comment by grunch** [comment]
Hi, I have a very noob question, sorry about that, just to be clear, this issue is referring to do something like this:
```
#[derive(Clone, Debug, PartialEq)]
pub struct LightningTimestamp(u32);
```
And change timestamps on LN messages from u32 to this new struct?

**Comment by dr-orlovsky** [comment]
@grunch yes, you are right. But we also need much more of the following:
- more derives (`Wrapper, Hash, Eq, PartialOrd, Ord`)
- custom Default implementation such that it will create current timestamp
- conversions from/to `chrono`-defined types
- operations specific to u32 which make sense for time (addition, probably subtraction)
- strict and lightning encodings (do not remember does LN encodes timestamp differently than u32; if it doesn't, just auto derivation will work)

As for the naming, just `Timestamp` will work

**Comment by dr-orlovsky** [comment]
~~Or, as an alternative, pls look into `chrono` timestamp related type; if it is backed by `u32` it may work and we just need to implement lightning encoding on (you can put it inside `encoding` crate folder within this repo)~~

UPD: just checked; no, it doesn't

**Comment by grunch** [comment]
Thanks for the proper response, I'll be working on it
