### ISSUE TITLE
Unknown even feature flag with number

### ISSUE THREAD

**Issue by oacdutra** [LNP-BP/lnp-core#23]
**Context**

When we try another LN implementations, the bolt9 integrity check fails.

- `unknown even feature flag with number 0`
- `unknown even feature flag with number 8`

Thanks

**Comment by dr-orlovsky** [comment]
This is a correct behavior. Can you clarify the issue please?

**Comment by oacdutra** [comment]
> This is a correct behavior. Can you clarify the issue please?

Yes, sure.

The checks fail when I tried connect with `clightning` or `lnd` nodes.

This issue is related with some information sent by other LN implementations and not handle in `flags` api.

**Comment by dr-orlovsky** [comment]
The BOLT document claims that when an even feature flag is provided by a remote, which is unknown to the local node, the local node must close the connection - and this is exactly what is happening. So this means that clightning doesn't work with nodes which do not support new features - and to fix it we need to implement the feature. So the issue should be defined in that way.

**Comment by oacdutra** [comment]
> The BOLT document claims that when an even feature flag is provided by a remote, which is unknown to the local node, the local node must close the connection - and this is exactly what is happening. So this means that clightning doesn't work with nodes which do not support new features - and to fix it we need to implement the feature. So the issue should be defined in that way.

Nice!

I will try map what these features occurs this error and prioritize the implementation, ok?

Thanks so much to the explanation. For now, I will close this issue.
